behaviors:
  SwarmTemplate:
    trainer_type: ppo

    max_steps: 5000000
    time_horizon: 64
    summary_freq: 1000
    keep_checkpoints: 5

    hyperparameters:
      batch_size: 32
      buffer_size: 200
      learning_rate: 0.0003
      learning_rate_schedule: linear

      beta: 0.05
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3

    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        